#!/bin/bash
#
# echo学习
# 版权 2025 peppa-pig

# Globals:
# Arguments:
#  None

: '
  echo的作用：
  1. 信息反馈
  2. 调试工具
  3. 交互界面
  4. 快速生成配置文件或脚本
'

#简单文本输出
echo "hello world!"

# 输出变量
name="张三"
echo "输出变量name：$name"

# 不带引号输出
echo this is a test

# 不换行输出，echo默认会在末尾加上换行符，通过-n参数去取消这一行为
echo -n "取消echo换行符： hello"
echo "world"

# 启用转义字符解释 -e 转义字符：\n：换行,\t:水平制表符，\v垂直制表符，\b:退格，\r:回车，\\：反斜杠字符本身
echo -e "First line...\nSecond line..."

# 使用重定向将输出的内容保存到文件当中,文件不存在会自动创建
#echo "save file info" > output.txt
## 向文件追加内容，没有文件会自动创建
#echo "this Is add info" >> output1.txt

# 输出命令执行结果
echo "Tody is $(date)"
# 进度条模拟
echo -n "Progress: ["
for i in {1..20}; do
    echo -n "#"
    sleep 0.1
done
echo "] Done!"
