#!/bin/bash
# 传递参数
# 版权 2025 peppa-pig

echo "Shell 传递参数实例"
echo "执行的文件名称：$0"
echo "第一个参数：$1"
echo "第二个参数：$2"
echo "第三个参数：$3"

echo "Shell 参数传递实例！"
echo "第一个参数：$1"
echo "参数数量：$#"
echo "传递参数作为一个字符串展示：$*"

: '
  $@和$*的区别：
  - 相同点：都是引用所有的参数
  - 不同点：只有在""才可以显示出来不同点，例如参数1 2 3 $*相当于参数为"1 2 3"，而$@相当于参数"1" "2" "3"
'
echo "Shell 参数传递训练——\$@和\$*的区别"
echo "\$@演示"
for i in "$@"; do
  echo $i
done
echo "\$*演示"

for i in "$*"; do
  echo $i
done




