#!/bin/bash

: '
  函数学习
  注意：在shell中0表示true，其他数值表示false
  获取参数处理：
    1. $@：获取所有参数
    2. $*: 获取所有参数
    3. $?：获取函数返回值，不可以多次获取
    4. $$：获取当前进程的ID号
'

firstFunc() {
  echo "Shell 第一个函数"
}
# 2数相加
add(){
  n1=$1
  n2=$2
  echo "接收到的第一个参数:$n1"
  echo "接受到的第二个参数：$n2"
  return `expr $n1 + $n2`
}
echo "调用第一个函数"
firstFunc
echo "第一个函数调用结束"
echo "2数相加"
add 1 2
echo "第一次读取返回值：" $?
echo "第二次读取返回值：" $?

